name: Build DOCX with Pandoc

on:
  push:
    branches: [ main ]
    paths:
      - 'output/**/*.md'
      - 'styles/reference.docx'
      - '.github/workflows/pandoc-docx.yml'
  workflow_dispatch:
    inputs:
      input_glob:
        description: 'Glob for Markdown files to convert'
        required: false
        default: 'output/**/*.md'

jobs:
  build-docx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - name: Convert Markdown to DOCX
        env:
          INPUT_GLOB: ${{ github.event.inputs.input_glob || 'output/**/*.md' }}
        run: |
          set -euo pipefail
          shopt -s globstar nullglob
          mkdir -p output-docx
          refdoc="styles/reference.docx"
          count=0
          for md in $INPUT_GLOB; do
            base="$(basename "$md" .md)"
            out="output-docx/${base}.docx"
            if [ -f "$refdoc" ]; then
              pandoc "$md" -o "$out" --reference-doc="$refdoc"
            else
              pandoc "$md" -o "$out"
            fi
            echo "Wrote $out"
            count=$((count+1))
          done
          if [ "$count" -eq 0 ]; then
            echo "No Markdown files matched '$INPUT_GLOB'." >&2
            exit 1
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: docx-${{ github.sha }}
          path: output-docx/*.docx
      - name: Commit DOCX back to repo
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: add generated DOCX"
          file_pattern: output-docx/*.docx
